-- =============================================================================
-- 20260529_model_evolution.sql
-- Date: 2026-05-29
-- Purpose: Sprint 1 of the Agent Smith model-evolution refactor.
--   Brings the single source of truth (backend/app/core/model_catalog.py) into
--   the database for EXISTING installs. Adds catalog/capability columns to
--   llm_pricing, adds thinking_enabled to agents, upserts all 61 catalog rows,
--   marks legacy models as non-selectable (but keeps them billable), and remaps
--   orphan "Outros" agents to their OpenRouter equivalents.
--
-- IDEMPOTENT: safe to run multiple times. Every ALTER uses IF NOT EXISTS; the
--   upsert is ON CONFLICT DO UPDATE; the remaps are guarded by EXISTS checks.
--
-- BILLING SAFETY (critical user constraint):
--   * The UPSERT's DO UPDATE deliberately DOES NOT touch sell_multiplier nor
--     is_active, so community price customization and billing state survive.
--   * No price row is ever deleted; legacy rows remain is_active=true.
--
-- The section (b) INSERT block and supabase/seed_llm_pricing.sql are BOTH
--   generated by backend/scripts/gen_pricing_sql.py from the catalog, so they
--   can never drift. Re-generate after any catalog change.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- (a) Schema: new columns (all idempotent)
-- -----------------------------------------------------------------------------
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS selectable boolean DEFAULT true;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS tier varchar(20);
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS is_recommended boolean DEFAULT false;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS supports_temperature boolean DEFAULT true;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS supports_reasoning_effort boolean DEFAULT false;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS supports_thinking boolean DEFAULT false;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS thinking_api varchar(20);
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS supports_vision boolean DEFAULT false;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS supports_tools boolean DEFAULT true;
ALTER TABLE public.llm_pricing ADD COLUMN IF NOT EXISTS supports_verbosity boolean DEFAULT false;

ALTER TABLE public.agents ADD COLUMN IF NOT EXISTS thinking_enabled boolean DEFAULT false;

-- -----------------------------------------------------------------------------
-- (b) Upsert all 61 catalog rows.
--     GENERATED by backend/scripts/gen_pricing_sql.py --rows-only.
--     DO UPDATE refreshes prices/unit/provider/display_name/selectable/tier/
--     is_recommended and all capability columns, but NEVER sell_multiplier or
--     is_active (preserve community customization + billing state).
-- -----------------------------------------------------------------------------
INSERT INTO public.llm_pricing (
    model_name,
    input_price_per_million,
    output_price_per_million,
    unit,
    provider,
    display_name,
    is_active,
    selectable,
    tier,
    is_recommended,
    supports_temperature,
    supports_reasoning_effort,
    supports_thinking,
    thinking_api,
    supports_vision,
    supports_tools,
    supports_verbosity
) VALUES
    ('claude-opus-4-8', 5.0, 25.0, 'token', 'anthropic', 'Opus 4.8', true, true, 'premium', false, true, false, true, 'anthropic', true, true, false),
    ('claude-opus-4-7', 5.0, 25.0, 'token', 'anthropic', 'Opus 4.7', true, true, 'premium', false, true, false, true, 'anthropic', true, true, false),
    ('claude-sonnet-4-6', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 4.6', true, true, 'balanced', true, true, false, true, 'anthropic', true, true, false),
    ('claude-haiku-4-5', 1.0, 5.0, 'token', 'anthropic', 'Haiku 4.5', true, true, 'fast', false, true, false, true, 'anthropic', true, true, false),
    ('gpt-5.5', 5.0, 30.0, 'token', 'openai', 'GPT-5.5', true, true, 'premium', false, false, true, false, NULL, true, true, true),
    ('gpt-5.4', 2.5, 15.0, 'token', 'openai', 'GPT-5.4', true, true, 'balanced', true, false, true, false, NULL, true, true, true),
    ('gpt-5.4-mini', 0.75, 4.5, 'token', 'openai', 'GPT-5.4 Mini', true, true, 'fast', false, false, true, false, NULL, true, true, true),
    ('o3', 2.0, 8.0, 'token', 'openai', 'o3', true, true, 'reasoning', false, false, true, false, NULL, true, true, false),
    ('o3-pro', 20.0, 80.0, 'token', 'openai', 'o3 Pro', true, true, 'reasoning', false, false, true, false, NULL, true, true, false),
    ('o4-mini', 1.1, 4.4, 'token', 'openai', 'o4 Mini', true, true, 'reasoning', false, false, true, false, NULL, true, true, false),
    ('gemini-3.5-flash', 1.5, 9.0, 'token', 'google', 'Gemini 3.5 Flash', true, true, 'balanced', false, true, false, true, 'level', true, true, false),
    ('gemini-3.1-pro-preview', 2.0, 12.0, 'token', 'google', 'Gemini 3.1 Pro', true, true, 'premium', false, true, false, true, 'level', true, true, false),
    ('gemini-3.1-flash-lite', 0.25, 1.5, 'token', 'google', 'Gemini 3.1 Flash Lite', true, true, 'fast', false, true, false, true, 'level', true, true, false),
    ('gemini-2.5-pro', 1.25, 10.0, 'token', 'google', 'Gemini 2.5 Pro', true, true, 'premium', false, true, false, true, 'budget', true, true, false),
    ('gemini-2.5-flash', 0.3, 2.5, 'token', 'google', 'Gemini 2.5 Flash', true, true, 'fast', true, true, false, true, 'budget', true, true, false),
    ('claude-opus-4-6', 5.0, 25.0, 'token', 'anthropic', 'Opus 4.6', true, false, 'premium', false, true, false, true, 'anthropic', true, true, false),
    ('claude-opus-4-5', 5.0, 25.0, 'token', 'anthropic', 'Opus 4.5', true, false, 'premium', false, true, false, true, 'anthropic', true, true, false),
    ('claude-sonnet-4-5', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 4.5', true, false, 'balanced', false, true, false, true, 'anthropic', true, true, false),
    ('claude-opus-4-1-20250805', 15.0, 75.0, 'token', 'anthropic', 'Opus 4.1', true, false, 'premium', false, true, false, true, 'anthropic', true, true, false),
    ('claude-3-7-sonnet-20250219', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 3.7', true, false, 'balanced', false, true, false, true, 'anthropic', true, true, false),
    ('claude-3-5-haiku-20241022', 0.8, 4.0, 'token', 'anthropic', 'Haiku 3.5', true, false, 'fast', false, true, false, false, NULL, true, true, false),
    ('gpt-5.2', 1.75, 14.0, 'token', 'openai', 'GPT-5.2', true, false, 'balanced', false, false, true, false, NULL, true, true, true),
    ('gpt-5.1', 1.25, 10.0, 'token', 'openai', 'GPT-5.1', true, false, 'balanced', false, false, true, false, NULL, true, true, true),
    ('o3-mini', 1.0, 4.0, 'token', 'openai', 'o3 Mini', true, false, 'reasoning', false, false, true, false, NULL, false, true, false),
    ('o1', 15.0, 60.0, 'token', 'openai', 'o1', true, false, 'reasoning', false, false, true, false, NULL, true, true, false),
    ('gpt-4o', 2.5, 10.0, 'token', 'openai', 'GPT-4o', true, false, 'balanced', false, true, false, false, NULL, true, true, false),
    ('gpt-4o-mini', 0.15, 0.6, 'token', 'openai', 'GPT-4o Mini', true, false, 'fast', false, true, false, false, NULL, true, true, false),
    ('gemini-3-pro-preview', 2.0, 8.0, 'token', 'google', 'Gemini 3 Pro', true, false, 'premium', false, true, false, true, 'level', true, true, false),
    ('gemini-2.5-flash-lite', 0.05, 0.2, 'token', 'google', 'Gemini 2.5 Flash Lite', true, false, 'fast', false, true, false, true, 'budget', true, true, false),
    ('gemini-1.5-pro', 1.25, 5.0, 'token', 'google', 'Gemini 1.5 Pro', true, false, 'premium', false, true, false, false, NULL, true, true, false),
    ('gemini-1.5-flash', 0.075, 0.3, 'token', 'google', 'Gemini 1.5 Flash', true, false, 'fast', false, true, false, false, NULL, true, true, false),
    ('claude-haiku-4-5-20251001', 1.0, 5.0, 'token', 'anthropic', 'Haiku 4.5', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('claude-opus-4-5-20251101', 5.0, 25.0, 'token', 'anthropic', 'Opus 4.5', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('claude-sonnet-4-5-20250929', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 4.5', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('claude-opus-4-20250514', 15.0, 75.0, 'token', 'anthropic', 'Opus 4', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('claude-sonnet-4-20250514', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 4', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('claude-3-5-sonnet-20241022', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 3.5', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('claude-3-5-sonnet-20240620', 3.0, 15.0, 'token', 'anthropic', 'Sonnet 3.5', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('gpt-5.2-pro', 21.0, 168.0, 'token', 'openai', 'GPT-5.2 Pro', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('gpt-5.2-chat-latest', 1.75, 14.0, 'token', 'openai', 'GPT-5.2 Chat', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('chatgpt-4o-latest', 5.0, 15.0, 'token', 'openai', 'ChatGPT-4o', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('gpt-4o-mini-2024-07-18', 0.15, 0.6, 'token', 'openai', 'GPT-4o Mini', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('o1-pro', 30.0, 120.0, 'token', 'openai', 'o1 Pro', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('o1-mini', 3.0, 12.0, 'token', 'openai', 'o1 Mini', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('o1-preview', 15.0, 60.0, 'token', 'openai', 'o1 Preview', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('text-embedding-3-small', 0.02, 0.0, 'token', 'openai', 'Text Embedding 3 Small', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('whisper-1', 0.006, 0.0, 'minute', 'openai', 'Whisper', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('gemini-3-deep-think', 5.0, 20.0, 'token', 'google', 'Gemini 3 Deep Think', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('gemini-3-flash-preview', 0.1, 0.4, 'token', 'google', 'Gemini 3 Flash', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('grok-4', 2.0, 10.0, 'token', 'other', 'Grok 4', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('grok-3', 2.0, 10.0, 'token', 'other', 'Grok 3', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('deepseek-chat', 0.5, 2.0, 'token', 'other', 'DeepSeek Chat', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('mistral-large-latest', 2.0, 6.0, 'token', 'other', 'Mistral Large', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('meta-llama/llama-3.1-405b-instruct', 2.0, 6.0, 'token', 'openrouter', 'Llama 3.1 405B Instruct', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('meta-llama/llama-3.1-70b-instruct', 0.52, 0.75, 'token', 'openrouter', 'Llama 3.1 70B Instruct', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('deepseek/deepseek-chat', 0.14, 0.28, 'token', 'openrouter', 'DeepSeek Chat', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('deepseek/deepseek-reasoner', 0.55, 2.19, 'token', 'openrouter', 'DeepSeek Reasoner', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('mistralai/mistral-large', 2.0, 6.0, 'token', 'openrouter', 'Mistral Large', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('x-ai/grok-2', 2.0, 10.0, 'token', 'openrouter', 'Grok 2', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('cohere/command-r-plus', 2.5, 10.0, 'token', 'openrouter', 'Command R+', true, false, NULL, false, false, false, false, NULL, false, false, false),
    ('qwen/qwen-2.5-72b-instruct', 0.36, 0.36, 'token', 'openrouter', 'Qwen 2.5 72B Instruct', true, false, NULL, false, false, false, false, NULL, false, false, false)
ON CONFLICT (model_name) DO UPDATE SET
    input_price_per_million    = EXCLUDED.input_price_per_million,
    output_price_per_million   = EXCLUDED.output_price_per_million,
    unit                       = EXCLUDED.unit,
    provider                   = EXCLUDED.provider,
    display_name               = EXCLUDED.display_name,
    selectable                 = EXCLUDED.selectable,
    tier                       = EXCLUDED.tier,
    is_recommended             = EXCLUDED.is_recommended,
    supports_temperature       = EXCLUDED.supports_temperature,
    supports_reasoning_effort  = EXCLUDED.supports_reasoning_effort,
    supports_thinking          = EXCLUDED.supports_thinking,
    thinking_api               = EXCLUDED.thinking_api,
    supports_vision            = EXCLUDED.supports_vision,
    supports_tools             = EXCLUDED.supports_tools,
    supports_verbosity         = EXCLUDED.supports_verbosity,
    updated_at                 = now();
    -- NOTE: sell_multiplier and is_active are intentionally NOT updated here,
    -- to preserve community price customization and billing state.

-- -----------------------------------------------------------------------------
-- (c) Mark all legacy (non-selectable) catalog models as selectable=false.
--     The upsert above already sets selectable per-row, but this explicit
--     statement enforces the Design Lock #1 rule independently and is the
--     authoritative guard. is_active is left untouched -> legacy stays billable.
-- -----------------------------------------------------------------------------
UPDATE public.llm_pricing
SET selectable = false
WHERE model_name IN (
    'claude-opus-4-6',
    'claude-opus-4-5',
    'claude-sonnet-4-5',
    'claude-opus-4-1-20250805',
    'claude-3-7-sonnet-20250219',
    'claude-3-5-haiku-20241022',
    'gpt-5.2',
    'gpt-5.1',
    'o3-mini',
    'o1',
    'gpt-4o',
    'gpt-4o-mini',
    'gemini-3-pro-preview',
    'gemini-2.5-flash-lite',
    'gemini-1.5-pro',
    'gemini-1.5-flash',
    'claude-haiku-4-5-20251001',
    'claude-opus-4-5-20251101',
    'claude-sonnet-4-5-20250929',
    'claude-opus-4-20250514',
    'claude-sonnet-4-20250514',
    'claude-3-5-sonnet-20241022',
    'claude-3-5-sonnet-20240620',
    'gpt-5.2-pro',
    'gpt-5.2-chat-latest',
    'chatgpt-4o-latest',
    'gpt-4o-mini-2024-07-18',
    'o1-pro',
    'o1-mini',
    'o1-preview',
    'text-embedding-3-small',
    'whisper-1',
    'gemini-3-deep-think',
    'gemini-3-flash-preview',
    'grok-4',
    'grok-3',
    'deepseek-chat',
    'mistral-large-latest',
    'meta-llama/llama-3.1-405b-instruct',
    'meta-llama/llama-3.1-70b-instruct',
    'deepseek/deepseek-chat',
    'deepseek/deepseek-reasoner',
    'mistralai/mistral-large',
    'x-ai/grok-2',
    'cohere/command-r-plus',
    'qwen/qwen-2.5-72b-instruct'
);

-- -----------------------------------------------------------------------------
-- (d) Orphan-agent remap (Design Lock #4 / SPRINTS MAJOR-2).
--
--     Existing agents may have stored a bare "Outros" id as llm_model (grok-4,
--     grok-3, deepseek-chat, mistral-large-latest). These fall into the wrong
--     billing/factory path. We remap each to its OpenRouter slug and set
--     llm_provider='openrouter'. Each UPDATE is GUARDED by EXISTS so it only
--     fires when the target OpenRouter slug actually exists in llm_pricing
--     (it does, after section b).
--
--     If ZERO agents match (the normal case on a fresh install, and common on
--     existing installs that never used "Outros"), each statement is a no-op.
--     This is expected and not an error.
--
--     HUMAN REVIEW REQUIRED: grok-4 and grok-3 have no live OpenRouter slug in
--     our table (x-ai/grok-4 / x-ai/grok-3 are not present), so both are mapped
--     to the closest available slug 'x-ai/grok-2'. Confirm this mapping (pricing
--     and behavior differ from grok-4) before relying on it in production.
-- -----------------------------------------------------------------------------

-- grok-4 -> x-ai/grok-2  (HUMAN REVIEW: closest available slug, not exact grok-4)
UPDATE public.agents
SET llm_model = 'x-ai/grok-2', llm_provider = 'openrouter'
WHERE llm_model = 'grok-4'
  AND EXISTS (SELECT 1 FROM public.llm_pricing WHERE model_name = 'x-ai/grok-2');

-- grok-3 -> x-ai/grok-2  (HUMAN REVIEW: closest available slug, not exact grok-3)
UPDATE public.agents
SET llm_model = 'x-ai/grok-2', llm_provider = 'openrouter'
WHERE llm_model = 'grok-3'
  AND EXISTS (SELECT 1 FROM public.llm_pricing WHERE model_name = 'x-ai/grok-2');

-- deepseek-chat -> deepseek/deepseek-chat
UPDATE public.agents
SET llm_model = 'deepseek/deepseek-chat', llm_provider = 'openrouter'
WHERE llm_model = 'deepseek-chat'
  AND EXISTS (SELECT 1 FROM public.llm_pricing WHERE model_name = 'deepseek/deepseek-chat');

-- mistral-large-latest -> mistralai/mistral-large
UPDATE public.agents
SET llm_model = 'mistralai/mistral-large', llm_provider = 'openrouter'
WHERE llm_model = 'mistral-large-latest'
  AND EXISTS (SELECT 1 FROM public.llm_pricing WHERE model_name = 'mistralai/mistral-large');

-- Catch-all safety net: any remaining agent whose provider is outside the four
-- known providers AND whose model happens to match an OpenRouter slug already in
-- llm_pricing gets its provider corrected to 'openrouter'. Guarded so it only
-- touches rows with a real pricing match; otherwise a no-op. Bare ids handled
-- above are already remapped, so they will not be caught here.
UPDATE public.agents a
SET llm_provider = 'openrouter'
WHERE a.llm_provider IS NOT NULL
  AND a.llm_provider NOT IN ('openai', 'anthropic', 'google', 'openrouter')
  AND EXISTS (
        SELECT 1 FROM public.llm_pricing p
        WHERE p.model_name = a.llm_model
          AND p.provider = 'openrouter'
  );

COMMIT;
