-- =============================================================================
-- 20260628_02_openrouter_models_refresh.sql
-- Date: 2026-06-28
-- Purpose: Refresh the OpenRouter section of the model catalog for EXISTING
--   installs. Brings the new owner-curated OpenRouter flagships into
--   public.llm_pricing, forces reasoning OFF for every OpenRouter row, and
--   hides the 2024-era legacy OpenRouter slugs from the selector.
--
--   Single source of truth is backend/app/core/model_catalog.py (CATALOG).
--   Section (b) below is the OpenRouter slice of the same gen_pricing_sql.py
--   output that produces supabase/seed_llm_pricing.sql, so seed and migration
--   can never drift. Fresh installs get this from the seed; this migration is
--   ONLY for installs that already ran 20260529_model_evolution.sql.
--
-- IDEMPOTENT: safe to run multiple times. The upsert is ON CONFLICT DO UPDATE;
--   the UPDATEs are set-to-constant and converge.
--
-- BILLING SAFETY (critical owner constraint):
--   * The UPSERT's DO UPDATE deliberately DOES NOT touch sell_multiplier nor
--     is_active, so community price customization and billing state survive.
--   * No price row is ever deleted. Legacy OpenRouter rows stay is_active=true
--     (still billable for history); they are only set selectable=false.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- (b) Upsert the new owner-curated OpenRouter flagships.
--     GENERATED by backend/scripts/gen_pricing_sql.py (OpenRouter slice).
--     IDs/slugs and prices are the EXACT live OpenRouter API values
--     (2026-06-28). reasoning_effort is false for every row (owner decision).
--     DO UPDATE refreshes prices/unit/provider/display_name/selectable/tier/
--     is_recommended and all capability columns, but NEVER sell_multiplier or
--     is_active (preserve community customization + billing state).
-- -----------------------------------------------------------------------------
INSERT INTO public.llm_pricing (
    model_name,
    input_price_per_million,
    output_price_per_million,
    unit,
    provider,
    display_name,
    is_active,
    selectable,
    tier,
    is_recommended,
    supports_temperature,
    supports_reasoning_effort,
    supports_thinking,
    thinking_api,
    supports_vision,
    supports_tools,
    supports_verbosity
) VALUES
    ('z-ai/glm-5.2', 0.95, 3.0, 'token', 'openrouter', 'GLM 5.2', true, true, 'premium', false, true, false, false, NULL, false, true, false),
    ('z-ai/glm-5.1', 0.98, 3.08, 'token', 'openrouter', 'GLM 5.1', true, true, 'balanced', false, true, false, false, NULL, false, true, false),
    ('deepseek/deepseek-v4-pro', 0.435, 0.87, 'token', 'openrouter', 'DeepSeek V4 Pro', true, true, 'premium', false, true, false, false, NULL, false, true, false),
    ('deepseek/deepseek-v4-flash', 0.09, 0.18, 'token', 'openrouter', 'DeepSeek V4 Flash', true, true, 'fast', false, true, false, false, NULL, false, true, false),
    ('minimax/minimax-m3', 0.3, 1.2, 'token', 'openrouter', 'MiniMax M3', true, true, 'balanced', false, true, false, false, NULL, true, true, false),
    ('qwen/qwen3.7-max', 1.25, 3.75, 'token', 'openrouter', 'Qwen 3.7 Max', true, true, 'premium', false, true, false, false, NULL, false, true, false),
    ('moonshotai/kimi-k2.6', 0.66, 3.41, 'token', 'openrouter', 'Kimi K2.6', true, true, 'balanced', false, true, false, false, NULL, true, true, false),
    ('x-ai/grok-4.3', 1.25, 2.5, 'token', 'openrouter', 'Grok 4.3', true, true, 'premium', false, true, false, false, NULL, true, true, false),
    ('meta-llama/llama-4-maverick', 0.15, 0.6, 'token', 'openrouter', 'Llama 4 Maverick', true, true, 'balanced', false, true, false, false, NULL, true, true, false)
ON CONFLICT (model_name) DO UPDATE SET
    input_price_per_million    = EXCLUDED.input_price_per_million,
    output_price_per_million   = EXCLUDED.output_price_per_million,
    unit                       = EXCLUDED.unit,
    provider                   = EXCLUDED.provider,
    display_name               = EXCLUDED.display_name,
    selectable                 = EXCLUDED.selectable,
    tier                       = EXCLUDED.tier,
    is_recommended             = EXCLUDED.is_recommended,
    supports_temperature       = EXCLUDED.supports_temperature,
    supports_reasoning_effort  = EXCLUDED.supports_reasoning_effort,
    supports_thinking          = EXCLUDED.supports_thinking,
    thinking_api               = EXCLUDED.thinking_api,
    supports_vision            = EXCLUDED.supports_vision,
    supports_tools             = EXCLUDED.supports_tools,
    supports_verbosity         = EXCLUDED.supports_verbosity,
    updated_at                 = now();
    -- NOTE: sell_multiplier and is_active are intentionally NOT updated here,
    -- to preserve community price customization and billing state.

-- -----------------------------------------------------------------------------
-- (c) REASONING OFF for ALL OpenRouter rows (owner decision).
--     The admin "Sync OpenRouter" button used to derive reasoning_effort from
--     the API ("reasoning" in supported_parameters), which turned it ON for
--     several slugs (deepseek-r1/v3.2, minimax-m2.x, kimi-k2.5, qwen3-235b,
--     glm-4.5-air/4.7/5, nemotron...). Until the reasoning path is validated,
--     force it OFF for every OpenRouter row. pricing.py now also pins this on
--     Sync so the button cannot re-enable it.
-- -----------------------------------------------------------------------------
UPDATE public.llm_pricing
SET supports_reasoning_effort = false,
    updated_at = now()
WHERE provider = 'openrouter'
  AND supports_reasoning_effort IS DISTINCT FROM false;

-- -----------------------------------------------------------------------------
-- (d) Hide the 2024-era legacy OpenRouter slugs from the selector.
--     is_active is left untouched -> they stay billable for history. They are
--     only removed from the dropdown (selectable=false).
-- -----------------------------------------------------------------------------
UPDATE public.llm_pricing
SET selectable = false,
    updated_at = now()
WHERE provider = 'openrouter'
  AND model_name IN (
    'meta-llama/llama-3.1-405b-instruct',
    'meta-llama/llama-3.1-70b-instruct',
    'deepseek/deepseek-chat',
    'deepseek/deepseek-reasoner',
    'mistralai/mistral-large',
    'x-ai/grok-2',
    'cohere/command-r-plus',
    'qwen/qwen-2.5-72b-instruct'
  )
  AND selectable IS DISTINCT FROM false;

COMMIT;
